### ISSUE TITLE
Bug where manually created planet isn't getting found for spawning

### ISSUE THREAD

**Issue by cha0sg0d** [dfdao/client#19]
`all manually created spawn planets: 1eadbeef00000000b5b89a8cf969a4fc33387b6bf99cacccc1db5b54d85319b0`

<img width="564" alt="Screen Shot 2022-04-22 at 2 26 08 PM" src="https://user-images.githubusercontent.com/42984734/164713990-1553b60c-43a1-48d0-b678-a42dad9d02c4.png">

**Comment by cha0sg0d** [comment]
w manual spawn created at (0,0)

**Comment by cha0sg0d** [comment]
Can't reproduce, will try to figure it out and update the issue

**Comment by cha0sg0d** [comment]
Ok getting it again (4/27)

So I try to create 2 spawn planets (-4000,0) (0,4000) and one target (0,0)

When I inspect the revealed planets, I see spawn at (-4000,0) and target at (0,0).

The third one, with id: "1eadbeef00000000b5b89a8cf969a4fc33387b6bf99cacccc1db5b54d85319b0", also says coords (0,0) and doesn't have target or spawn planet set to true.

**Comment by cha0sg0d** [comment]
I tried again on a new lobby and didn't have this problem. I have one guess -> this happens because some old data is still in the index db on `localhost:8081` and is getting used instead of the newly created planet. Shouldn't be an issue in prod, but still worth keeping an eye on.

**Comment by cha0sg0d** [comment]
On second thought, I'm not sure that we won't have this issue in prod. Will be worth testing as part of our play test

**Comment by cha0sg0d** [comment]
On third thought, I think the bug is that when ZK off, the planet ids don't change (incl admin reated plantes) because fakeHash don't take a random seed as input. Still not sure exactly why this is a problem, because I thought each indexDB is unique to that specific universe. Also, we should revisit how we get spawn planets in`InitialStateDownloader.tsx` and `joinGame` because its kind of janky

**Comment by 0xhank** [comment]
i got this issue with zk on. I think it happens when localstorage thinks it has saved map data already and it sets the lobby's map to that data. This means it never catches that a new admin planet was created and the new planet doesn't register on initialization.
